[project]
name = "cpkg"
version = "0.1.0"
description = "C python package test"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cython>=3.1.3",

]

[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "Cython>=3.1.3"
]
build-backend = "setuptools.build_meta"

[[tool.setuptools.ext-modules]]
name = "helloworld_ext"
sources = [
    "src/cpkg/helloworld_ext.pyx",
    "src/cpkg/helloworld.c"
]
include-dirs = ["src/cpkg"]

[[tool.setuptools.ext-modules]]
name = "cpkg.prime_ext"
sources = [
    "src/cpkg/prime_ext.pyx",
    "src/cpkg/prime.c"
]
include-dirs = ["src/cpkg"]

extra-compile-args = ["-fopenmp", "-O2"]
extra-link-args = ["-fopenmp"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]

[tool.setuptools.package-dir]
"" = "src"