[project]
name = "pythonpkg"
version = "0.1.0"
description = "A python code of cpppkg function"
license = {text = "MIT"}
authors = [
    {name = "quantumxiaol"}
]
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"